"""
acados_mpcc_solver.py
=====================

Model Predictive Contouring Control (MPCC) for an HMMWV on Soil
Contact Model (SCM) terrain.

Why MPCC (and what's different from the standard MPC in
``acados_mpc_solver.py``)
--------------------------------------------------------------
The standard formulation tracks a *time-parametrised* reference
``(x_ref(t), y_ref(t), ψ_ref(t), v_ref(t))``.  The reference speed
``v_ref(t)`` is generated by ``reference_path.py`` from path
curvature alone — it ignores the *friction ellipse* (longitudinal
and lateral tire-force budgets share the same μ·g envelope) and is
pre-computed open-loop.  In closed-loop driving on low-traction
SCM terrain (clay μ ≈ 0.23 → ay_max ≈ 2.3 m/s²), the reference is
often *infeasible*: the speed profile assumes a constant
``a_brake = 2.0 m/s²`` and ``a_accel = 3.0 m/s²`` *independent* of
lateral demand, but at cornering near ay_max the longitudinal
authority is essentially zero.  The MPC ends up fighting itself —
chasing an unreachable v_ref and sacrificing path tracking.

MPCC drops the speed reference entirely.  The path is just the
*spatial* curve ``(x_p(θ), y_p(θ))``.  ``θ`` (arc-length along the
path) is added to the state, and ``vθ = θ̇`` becomes a *control
input*.  The optimizer picks ``vθ`` itself, subject to:

* dynamics (bicycle + NN-surrogate Fy);
* actuator bounds;
* the *friction ellipse*:
  ``(Fx_total / Fx_max)² + (Fy_total / Fy_max)² ≤ 1``
  evaluated symbolically on NN tire forces at every stage.

Cost (NO speed reference):

    J = Σ_k [ w_c · e_c²(k) + w_l · e_l²(k) − w_prog · vθ(k)
              + control regularisation(k) ]

with the contour and lag errors

    e_c =  (px − x_p(θ)) · sin(ψ_p) − (py − y_p(θ)) · cos(ψ_p)   (lateral)
    e_l = −(px − x_p(θ)) · cos(ψ_p) − (py − y_p(θ)) · sin(ψ_p)   (longitudinal)

and the progress reward ``−w_prog · vθ``.  In a curve, the friction
ellipse binds, capping ``vθ``; on a straight, the optimizer pushes
``vθ`` up to the actuator limit.  This is the same formulation
used in Liniger et al. (2015) and the F1Tenth racing MPC stack.

Path representation
-------------------
The full path ``(x_p(θ), y_p(θ), ψ_p(θ))`` is a cubic spline in
``ReferencePath``.  We can't embed a spline inside CasADi directly,
so at each solve the controller node samples the spline at the
*predicted* θ trajectory (warm-started from last solve) and passes
the four parameters ``(x_p_k, y_p_k, sin_ψ_p_k, cos_ψ_p_k)`` per
stage.  One outer iteration is enough in practice — the predicted
θ trajectory rarely diverges far from the actual one because
``θ̇ = vθ`` is bounded.

State / control / parameter layout
----------------------------------
State (10):  [x, y, ψ, u, v, ω, ax, δ_prev, Jx_prev, θ]
Control (3): [δ, Jx, vθ]
Parameters per stage (small + interpretable):
  (x_p, y_p, sin_ψ_p, cos_ψ_p,
   Kphi, Kc, n_terrain, c, phi (rad), k_janosi)
"""

from __future__ import annotations

import os
from pathlib import Path

import casadi as ca
import numpy as np

# ACADOS needs to know where its C library lives (same preamble as
# ``acados_mpc_solver.py`` — see that file for the rationale).
_ACADOS_SOURCE = os.environ.get('ACADOS_SOURCE_DIR', os.path.expanduser('~/acados'))
os.environ.setdefault('ACADOS_SOURCE_DIR', _ACADOS_SOURCE)
os.environ['LD_LIBRARY_PATH'] = (
    os.path.join(_ACADOS_SOURCE, 'lib') + ':' + os.environ.get('LD_LIBRARY_PATH', ''))

import ctypes
_acados_lib_dir = os.path.join(_ACADOS_SOURCE, 'lib')
for _lib_name in ['libblasfeo.so', 'libhpipm.so', 'libqpOASES_e.so', 'libacados.so']:
    _lib_path = os.path.join(_acados_lib_dir, _lib_name)
    if os.path.isfile(_lib_path):
        ctypes.CDLL(_lib_path, mode=ctypes.RTLD_GLOBAL)

from acados_template import AcadosModel, AcadosOcp, AcadosOcpSolver
from param_consistency import HMMWV_VEHICLE_PARAMS


DEFAULT_DT = 0.1
DEFAULT_N = 20


# ----------------------------------------------------------------------------
# MPCC solver
# ----------------------------------------------------------------------------


class AcadosMPCC:
    """Model Predictive Contouring Control on the SCM HMMWV.

    Notes
    -----
    * Uses the *same* NN tire surrogate as the standard MPC — the
      surrogate is required, no analytical-tire fallback.  This is
      intentional: MPCC's friction-ellipse constraint needs the
      same Fx/Fy that the dynamics use, otherwise the constraint
      can clip a *feasible* trajectory because the constraint
      Fx_max disagrees with the dynamics' produced Fx.

    * Stage parameters embed the *path samples* (x_p, y_p, sinψ_p,
      cosψ_p) at the predicted θ_k — these are updated each solve
      by the controller node via ``set_path_samples``.
    """

    NX = 9            # [x, y, ψ, u, v, ω, ax, δ, θ]
    NU = 3            # [δ_dot, jx, vθ]
    N_PATH = 4        # (x_p, y_p, sinψ_p, cosψ_p) per stage
    N_TERRAIN = 6     # (Kphi, Kc, n, c, phi_rad, k)
    N_VMAX = 1        # curvature-derived speed cap at this stage
    NP = N_PATH + N_TERRAIN + N_VMAX  # 11 parameters per stage

    # State indices (named for clarity)
    IX = 0; IY = 1; IPSI = 2
    IU = 3; IV = 4; IOMEGA = 5
    IAX = 6; IDELTA = 7
    ITHETA = 8

    def __init__(
        self,
        nn_tire_model,
        terrain_params: dict,
        dt: float = DEFAULT_DT,
        N: int = DEFAULT_N,
        # Cost weights.  The *relative* magnitudes matter most:
        #
        #   w_lag : w_progress ≈ 1000:1
        #
        # is the standard MPCC balance.  Lag (longitudinal mismatch
        # between the vehicle and the path-at-θ) physically couples
        # ``vθ`` to the actual speed ``u`` along the path — without
        # heavy lag the optimizer drives ``vθ`` to its upper bound
        # while the vehicle barely accelerates, growing the lag
        # unbounded and breaking the QP.  Contour is also heavy so
        # the vehicle stays on the path.  Progress weight is tiny —
        # just enough to break ties between stationary solutions.
        w_contour: float = 3000.0,
        w_lag: float = 2000.0,
        w_progress: float = 0.5,
        w_delta_dot: float = 80.0,
        w_jx: float = 5.0,
        w_steer: float = 5.0,
        # Speed-cap penalty (one-sided quadratic when u > v_max_stage).
        # The optimizer's progress reward pushes ``vθ`` (and via the
        # heavy lag cost, ``u`` along the path) upward; this term caps
        # ``u`` at the curvature-derived limit without imposing a hard
        # equality reference.  Acts like a "soft constraint".
        w_speed_cap: float = 300.0,
        # Friction-ellipse safety margins
        mu_safety: float = 0.85,
        friction_ellipse: bool = False,
        # Actuator / state bounds (HMMWV defaults)
        delta_max: float = 0.528,
        delta_dot_max: float = 1.0,
        ax_min: float = -3.0,
        ax_max: float = 2.5,
        jx_min: float = -3.0,
        jx_max: float = 3.0,
        vtheta_max: float = 5.0,   # m/s — matched to typical v_target; lag-cost + soft v_max keep vθ below this
        verbose: bool = False,
    ):
        if nn_tire_model is None:
            raise ValueError("AcadosMPCC requires nn_tire_model (no analytical fallback).")
        self.nn = nn_tire_model
        self.terrain_params = dict(terrain_params)
        self.dt = float(dt)
        self.N = int(N)

        self.w_contour = float(w_contour)
        self.w_lag = float(w_lag)
        self.w_progress = float(w_progress)
        self.w_delta_dot = float(w_delta_dot)
        self.w_jx = float(w_jx)
        self.w_steer = float(w_steer)
        self.w_speed_cap = float(w_speed_cap)
        self.mu_safety = float(mu_safety)
        self.friction_ellipse = bool(friction_ellipse)

        self.delta_max = float(delta_max)
        self.delta_dot_max = float(delta_dot_max)
        self.ax_min = float(ax_min); self.ax_max = float(ax_max)
        self.jx_min = float(jx_min); self.jx_max = float(jx_max)
        self.vtheta_max = float(vtheta_max)

        # Vehicle params (HMMWV)
        self.M = float(HMMWV_VEHICLE_PARAMS['M'])
        self.Izz = float(HMMWV_VEHICLE_PARAMS['Izz'])
        self.Lf = float(HMMWV_VEHICLE_PARAMS['Lf'])
        self.Lr = float(HMMWV_VEHICLE_PARAMS['Lr'])
        self.h_cg = float(HMMWV_VEHICLE_PARAMS.get('h_cg', 0.65))

        self.verbose = verbose
        self._solver = None
        self._last_z = None       # last predicted trajectory (for θ warm-start)
        self._build_ocp()

    # ------------------------------------------------------------------
    # OCP construction
    # ------------------------------------------------------------------

    def _build_ocp(self):
        ocp = AcadosOcp()
        ocp.dims.N = self.N

        # Symbols
        x_sym = ca.SX.sym('x', self.NX)
        u_sym = ca.SX.sym('u', self.NU)
        p_sym = ca.SX.sym('p', self.NP)
        xdot_sym = ca.SX.sym('xdot', self.NX)

        # Unpack
        px, py, psi = x_sym[self.IX], x_sym[self.IY], x_sym[self.IPSI]
        u_vel, v_vel, omega = x_sym[self.IU], x_sym[self.IV], x_sym[self.IOMEGA]
        ax = x_sym[self.IAX]
        delta = x_sym[self.IDELTA]
        theta = x_sym[self.ITHETA]

        delta_dot = u_sym[0]
        jx = u_sym[1]
        vtheta = u_sym[2]

        # Path samples (passed per stage by controller node)
        x_p   = p_sym[0]
        y_p   = p_sym[1]
        sin_p = p_sym[2]
        cos_p = p_sym[3]
        # Terrain (kept stage-uniform but passed per stage for future per-stage variation)
        Kphi  = p_sym[4]
        Kc    = p_sym[5]
        n_t   = p_sym[6]
        c     = p_sym[7]
        phi   = p_sym[8]
        k     = p_sym[9]
        # Curvature-derived speed cap at this stage's θ (m/s)
        v_max_stage = p_sym[10]

        # ---- Tire forces via NN ------------------------------------------------
        u_safe = ca.fmax(ca.fabs(u_vel), 0.5)
        alpha_f = delta - ca.atan2(v_vel + self.Lf * omega, u_safe)
        alpha_r = -ca.atan2(v_vel - self.Lr * omega, u_safe)
        _alpha_clip = 0.55
        alpha_f = ca.fmax(ca.fmin(alpha_f, _alpha_clip), -_alpha_clip)
        alpha_r = ca.fmax(ca.fmin(alpha_r, _alpha_clip), -_alpha_clip)

        # Normal loads with longitudinal weight transfer
        Fz_f_axle = (self.M * 9.81 * self.Lr - self.M * ax * self.h_cg) / (self.Lf + self.Lr)
        Fz_r_axle = (self.M * 9.81 * self.Lf + self.M * ax * self.h_cg) / (self.Lf + self.Lr)
        Fz_f_wheel = Fz_f_axle / 2.0
        Fz_r_wheel = Fz_r_axle / 2.0

        nn_fn = self.nn.predict_tire_force  # scalar symbolic
        # kappa held at 0 (longitudinal channel goes through u̇ = ax, not Fx_op)
        kappa = ca.SX(0.0)
        sr = ca.SX(0.0)
        # Front (per wheel)
        Fx_f, Fy_f = nn_fn(alpha_f, Fz_f_wheel, u_safe, kappa, n_t, sr,
                            Kphi, Kc, c, phi, k)
        # Rear (per wheel)
        Fx_r, Fy_r = nn_fn(alpha_r, Fz_r_wheel, u_safe, kappa, n_t, sr,
                            Kphi, Kc, c, phi, k)
        # Sign convention bridge — matches surrogate_dynamics.py and the
        # planning NMPC: NN labels are tire-frame Fy (negative for
        # positive slip).  Negate to get body-frame Fy.
        Fy_f = -Fy_f
        Fy_r = -Fy_r
        # Axle totals (×2 for left + right)
        Fyf_total = 2.0 * Fy_f
        Fyr_total = 2.0 * Fy_r
        Fx_total = self.M * ax   # longitudinal authority via integrator;
                                 # Fx_max budget enforced through ellipse below.

        # ---- Friction-ellipse constraint --------------------------------------
        # Per-axle peak available force (lateral): NN at moderate-slip query.
        # Use a query slip at 70 % of clip so we don't ask for *peak* force
        # at the saturation knee — gives ~10 % safety margin.
        alpha_query = 0.7 * _alpha_clip
        _, Fy_peak_f = nn_fn(alpha_query, Fz_f_wheel, u_safe, kappa, n_t, sr,
                              Kphi, Kc, c, phi, k)
        _, Fy_peak_r = nn_fn(alpha_query, Fz_r_wheel, u_safe, kappa, n_t, sr,
                              Kphi, Kc, c, phi, k)
        Fy_peak_axle_f = ca.fmax(ca.fabs(2.0 * Fy_peak_f), 500.0)
        Fy_peak_axle_r = ca.fmax(ca.fabs(2.0 * Fy_peak_r), 500.0)
        # Longitudinal peak: μ·g per axle * mass; μ from phi (radians).
        mu_terrain = ca.fmax(ca.tan(phi), 0.10)
        Fx_peak = self.mu_safety * mu_terrain * Fz_f_axle  # front-axle drive-train cap
        # The ellipse: (Fx/Fx_peak)² + (Fy/Fy_peak)² ≤ 1, per axle.
        # We require it for both axles (rear has Fx_total = 0 in our
        # bicycle parameterisation since ax is body-frame longitudinal
        # acceleration; rear axle just contributes to Fy, so its
        # constraint reduces to |Fyr_total| ≤ Fy_peak_axle_r — which the
        # NN model essentially enforces by saturation, but we add it
        # explicitly for the optimizer's gradient).
        h_ellipse_f = (Fx_total / Fx_peak) ** 2 + (Fyf_total / Fy_peak_axle_f) ** 2
        h_ellipse_r = (Fyr_total / Fy_peak_axle_r) ** 2

        # ---- Dynamics ---------------------------------------------------------
        # Bicycle EOMs with NN lateral forces; longitudinal via integrator
        # u̇ = ax, ȧx = jx (control jerk), δ̇ = δ_dot (control rate),
        # θ̇ = vθ.  This makes (δ, ax) actuator states the optimizer can
        # smooth via box bounds on δ_dot, jx without an extra Jx_prev
        # bookkeeping state.
        f_expl = ca.vertcat(
            u_vel * ca.cos(psi) - v_vel * ca.sin(psi),                # ẋ
            u_vel * ca.sin(psi) + v_vel * ca.cos(psi),                # ẏ
            omega,                                                     # ψ̇
            ax,                                                        # u̇
            (Fyf_total + Fyr_total) / self.M - u_vel * omega,          # v̇
            (Fyf_total * self.Lf - Fyr_total * self.Lr) / self.Izz,    # ω̇
            jx,                                                        # ȧx
            delta_dot,                                                 # δ̇
            vtheta,                                                    # θ̇
        )

        # ---- Acados model -----------------------------------------------------
        model = AcadosModel()
        model.name = 'hmmwv_mpcc'
        model.x = x_sym
        model.u = u_sym
        model.xdot = xdot_sym
        model.p = p_sym
        model.f_expl_expr = f_expl
        model.f_impl_expr = xdot_sym - f_expl
        ocp.model = model
        ocp.dims.nx = self.NX
        ocp.dims.nu = self.NU
        ocp.dims.np = self.NP

        # ---- Cost: external nonlinear cost -----------------------------------
        # Contour and lag errors at the path sample (x_p, y_p, sinψ_p, cosψ_p)
        e_c = -(px - x_p) * sin_p + (py - y_p) * cos_p              # lateral
        e_l =  (px - x_p) * cos_p + (py - y_p) * sin_p              # longitudinal

        # Soft speed cap: smooth approximation to max(0, u - v_max_stage)²
        # using softplus to keep the cost twice-differentiable for the
        # SQP Hessian.  Penalty is ~0 below the cap and ramps up
        # quadratically above.
        over = u_vel - v_max_stage
        soft_over = ca.if_else(over > 0, over * over, 0.0)
        stage_cost = (
            self.w_contour * e_c ** 2
            + self.w_lag * e_l ** 2
            - self.w_progress * vtheta
            + self.w_delta_dot * delta_dot ** 2
            + self.w_jx * jx ** 2
            + self.w_steer * delta ** 2
            + self.w_speed_cap * soft_over
        )
        terminal_cost = (
            self.w_contour * e_c ** 2 + self.w_lag * e_l ** 2
        )

        ocp.cost.cost_type = 'EXTERNAL'
        ocp.cost.cost_type_e = 'EXTERNAL'
        ocp.model.cost_expr_ext_cost = stage_cost
        ocp.model.cost_expr_ext_cost_e = terminal_cost

        # ---- Constraints ------------------------------------------------------
        # Control box bounds: δ_dot, jx, vθ
        ocp.constraints.lbu = np.array([-self.delta_dot_max, self.jx_min, 0.0])
        ocp.constraints.ubu = np.array([+self.delta_dot_max, self.jx_max, self.vtheta_max])
        ocp.constraints.idxbu = np.array([0, 1, 2])
        # State box bounds: speed, ax, δ
        ocp.constraints.lbx = np.array([0.0, self.ax_min, -self.delta_max])
        ocp.constraints.ubx = np.array([self.vtheta_max + 5.0, self.ax_max, +self.delta_max])
        ocp.constraints.idxbx = np.array([self.IU, self.IAX, self.IDELTA])

        # Nonlinear path constraint: friction ellipse (front + rear).
        # Disabled by default — NN-derived Fy_peak on closed-loop data
        # can be much smaller than the actual tire envelope (because
        # the NN sees averaged steady-state forces, not peaks), making
        # the constraint chronically infeasible.  Re-enable via
        # ``friction_ellipse=True`` once a peak-Fy probing strategy
        # that's robust to the surrogate's averaging bias is in place.
        if self.friction_ellipse:
            h_expr = ca.vertcat(h_ellipse_f, h_ellipse_r)
            ocp.model.con_h_expr = h_expr
            ocp.constraints.lh = np.array([-1e6, -1e6])
            ocp.constraints.uh = np.array([1.0, 1.0])

        # Initial state placeholder
        ocp.constraints.x0 = np.zeros(self.NX)

        # Parameters default (will be overwritten per stage at solve time)
        ocp.parameter_values = np.zeros(self.NP)

        # ---- Solver options ---------------------------------------------------
        ocp.solver_options.tf = self.dt * self.N
        ocp.solver_options.integrator_type = 'IRK'
        ocp.solver_options.sim_method_num_stages = 2
        ocp.solver_options.sim_method_num_steps = 1
        ocp.solver_options.nlp_solver_type = 'SQP_RTI'
        ocp.solver_options.hessian_approx = 'GAUSS_NEWTON'
        ocp.solver_options.qp_solver = 'PARTIAL_CONDENSING_HPIPM'
        ocp.solver_options.qp_solver_cond_N = max(self.N // 2, 5)
        ocp.solver_options.print_level = 0
        ocp.solver_options.regularize_method = 'PROJECT'
        ocp.solver_options.levenberg_marquardt = 1e-3

        # JSON gen dir (mirror the standard solver's convention)
        gen_dir = Path('/tmp') / f'acados_mpcc_{self.nn.model_type}'
        gen_dir.mkdir(parents=True, exist_ok=True)
        ocp.code_export_directory = str(gen_dir / 'c_generated_code')
        json_file = gen_dir / 'acados_ocp.json'

        if self.verbose:
            print(f'  [MPCC] Building solver under {gen_dir} ...')
        self._solver = AcadosOcpSolver(ocp, json_file=str(json_file), verbose=self.verbose)
        self.ocp = ocp

    # ------------------------------------------------------------------
    # Per-solve helpers
    # ------------------------------------------------------------------

    def _terrain_p(self) -> np.ndarray:
        tp = self.terrain_params
        return np.array([
            float(tp['Kphi']), float(tp['Kc']), float(tp['n']),
            float(tp['c']), float(np.radians(tp['phi'])), float(tp['k']),
        ])

    def set_path_samples(self, path_xy: np.ndarray, path_psi: np.ndarray,
                          v_max_stage: np.ndarray):
        """Push per-stage path samples + speed cap to the solver.

        Args
        ----
        path_xy : ``(N+1, 2)`` array of ``(x_p_k, y_p_k)`` for k = 0..N.
        path_psi: ``(N+1,)`` array of ``ψ_p_k``.
        v_max_stage: ``(N+1,)`` curvature-derived per-stage speed cap
            (m/s).  The soft-cost penalty kicks in when ``u`` exceeds
            this value.  Typically computed as ``sqrt(ay_max / κ(θ_k))``
            with a small safety margin.
        """
        assert path_xy.shape == (self.N + 1, 2)
        assert path_psi.shape == (self.N + 1,)
        assert v_max_stage.shape == (self.N + 1,)
        terrain = self._terrain_p()
        for k in range(self.N + 1):
            p = np.array([
                float(path_xy[k, 0]),
                float(path_xy[k, 1]),
                float(np.sin(path_psi[k])),
                float(np.cos(path_psi[k])),
                *terrain,
                float(v_max_stage[k]),
            ])
            self._solver.set(k, 'p', p)

    def update_terrain(self, terrain_params: dict):
        """Hot-swap terrain parameters (phi in degrees, internal convention)."""
        self.terrain_params = dict(terrain_params)

    def solve(self, z0: np.ndarray, path_xy: np.ndarray,
              path_psi: np.ndarray, v_max_stage: np.ndarray
              ) -> tuple[np.ndarray, np.ndarray, dict]:
        """Solve one MPCC step.

        Args
        ----
        z0 : initial augmented state ``(NX=9,)``.
        path_xy : ``(N+1, 2)`` per-stage path samples (caller supplies).
        path_psi: ``(N+1,)``.
        v_max_stage : ``(N+1,)`` curvature-derived speed cap per stage.

        Returns
        -------
        u0 : ``(NU,)`` first control action ``[δ_dot, jx, vθ]``.
        z_pred : ``(N+1, NX)`` predicted state trajectory.
        info : dict with solver status and timing.
        """
        z0 = np.asarray(z0, dtype=float).reshape(-1)
        assert z0.size == self.NX

        self.set_path_samples(path_xy, path_psi, v_max_stage)
        self._solver.set(0, 'lbx', z0)
        self._solver.set(0, 'ubx', z0)

        status = self._solver.solve()
        u0 = self._solver.get(0, 'u')
        z_pred = np.array([self._solver.get(k, 'x') for k in range(self.N + 1)])
        self._last_z = z_pred.copy()
        info = {
            'status': int(status),
            'solve_time_ms': 1000.0 * self._solver.get_stats('time_tot'),
            'kkt': float(self._solver.get_stats('residuals')[3]) if status == 0 else float('nan'),
            'cost': float(self._solver.get_cost()),
        }
        return u0, z_pred, info

    # ------------------------------------------------------------------
    # Convenience for warm-starting the path-sample θ trajectory
    # ------------------------------------------------------------------

    def predicted_theta(self) -> np.ndarray | None:
        """The most recent predicted θ trajectory for spline sampling.

        Returns ``None`` before the first ``solve`` call.
        """
        if self._last_z is None:
            return None
        return self._last_z[:, self.ITHETA].copy()
